-- Creación de tabla COMPANY
CREATE TABLE compania (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nombre VARCHAR2(100) NOT NULL,
                         creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Creación de tabla APP_USER
CREATE TABLE app_user (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          azure_oid VARCHAR2(50) NOT NULL,
                          email VARCHAR2(150) NOT NULL,
                          nombre VARCHAR2(100),
                          rol VARCHAR2(50) DEFAULT 'CLIENTE' NOT NULL,
                          activo NUMBER(1) DEFAULT 1 NOT NULL,
                          compania_id NUMBER NOT NULL,
                          creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          CONSTRAINT fk_user_company FOREIGN KEY (compania_id) REFERENCES company(id),
                          CONSTRAINT uq_azure_oid UNIQUE (azure_oid)
);

CREATE INDEX idx_app_user_email ON app_user(email);
CREATE INDEX idx_app_user_company ON app_user(compania_id);